#!/usr/bin/env bash

PID=/var/run/echod.pid

case "$1" in 
	start)
		if [ -e $PID ]; then
			echo "Already running"
			exit 1
		fi
		/opt/echo_s 1>/tmp/echo.log 2>&1 &
		echo $!>$PID
		;;
	stop)
		if [ ! -e $PID ]; then
			echo "Already stop"
			exit 1
		fi
		kill `cat $PID`
		rm $PID
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		if [ -e $PID ]; then
			echo daytime is running, pid=`cat $PID`
		else
			echo daytime is NOT running
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
